apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-api-deployment
  labels:
    app: cart-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cart-api
  template:
    metadata:
      labels:
        app: cart-api
    spec:
      containers:
      - name: cart-api
        image: cart-api:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cart-api-service
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 80
  selector:
    app: cart-api
